In [4]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series :",series)
print(type(series))

Series : 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
data = {'a':1,'b':2,'c':3}
series_data = pd.Series(data)
print(series_data)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [7]:
data = {'Name':['Shakeer','John','Jack'],
        'Age':[21,30,45],
        'City':['Banglore','NewYork','Florida']}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age      City
0  Shakeer   21  Banglore
1     John   30   NewYork
2     Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [18]:
data = [{'Name':'Skr','Age':32,'City':'Banglore'},
        {'Name':'john','Age':26,'City':'New York'},
        {'Name':'Jack','Age':30,'City':'Florida'}]

df = pd.DataFrame(data)
print(df)

   Name  Age      City
0   Skr   32  Banglore
1  john   26  New York
2  Jack   30   Florida

In [19]:
df['Name']

0     Skr
1    john
2    Jack
Name: Name, dtype: object

In [20]:
df.loc[0]

Name         Skr
Age           32
City    Banglore
Name: 0, dtype: object

In [21]:
df.iloc[0]

Name         Skr
Age           32
City    Banglore
Name: 0, dtype: object

In [24]:
print(df.at[2,'Age'])
print(df.at[2,'Name'])

30
Jack

In [26]:
df.iat[2,2]
df['Salary']=[5000,6000,7000]
df

   Name  Age      City  Salary
0   Skr   32  Banglore    5000
1  john   26  New York    6000
2  Jack   30   Florida    7000

In [27]:
df.drop('Salary',axis=1,inplace=True)
df

   Name  Age      City
0   Skr   32  Banglore
1  john   26  New York
2  Jack   30   Florida

In [31]:
df = pd.read_csv('sales_data.csv')
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [34]:
print('Datatypes:\n',df.dtypes)

Datatypes:
 Product_ID                int64
Sale_Date                object
Sales_Rep                object
Region                   object
Sales_Amount            float64
Quantity_Sold             int64
Product_Category         object
Unit_Cost               float64
Unit_Price              float64
Customer_Type            object
Discount                float64
Payment_Method           object
Sales_Channel            object
Region_and_Sales_Rep     object
dtype: object

In [35]:
print('Statistical Summary',df.describe())

Statistical Summary         Product_ID  Sales_Amount  Quantity_Sold    Unit_Cost   Unit_Price  \
count  1000.000000   1000.000000    1000.000000  1000.000000  1000.000000
mean   1050.128000   5019.265230      25.355000  2475.304550  2728.440120
std      29.573505   2846.790126      14.159006  1417.872546  1419.399839
min    1001.000000    100.120000       1.000000    60.280000   167.120000
25%    1024.000000   2550.297500      13.000000  1238.380000  1509.085000
50%    1051.000000   5019.300000      25.000000  2467.235000  2696.400000
75%    1075.000000   7507.445000      38.000000  3702.865000  3957.970000
max    1100.000000   9989.040000      49.000000  4995.300000  5442.150000

         Discount
count  1000.00000
mean      0.15239
std       0.08720
min       0.00000
25%       0.08000
50%       0.15000
75%       0.23000
max       0.30000

In [43]:
grouped = df.groupby(['Product_Category','Payment_Method'])['Sales_Amount'].mean()
print(grouped)

Product_Category  Payment_Method
Clothing          Bank Transfer     4936.053333
                  Cash              4893.542436
                  Credit Card       4873.454536
Electronics       Bank Transfer     5447.625443
                  Cash              4749.760000
                  Credit Card       4955.196186
Food              Bank Transfer     5744.160506
                  Cash              4892.313590
                  Credit Card       5309.918841
Furniture         Bank Transfer     4111.638681
                  Cash              5155.845632
                  Credit Card       5339.024390
Name: Sales_Amount, dtype: float64